### ISSUE TITLE
Time is not counted or reset when App is in background

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea-authenticator-ios#1]
Whenever the app is put into the background, the time “freezes” inside the app. That means; that if I then return to the app an hour later, the app is still counting down on that same code, which would be invalid.

Other authenticators resets their time (and therefore code) immediately when you open them up from the background – they are not waiting for the timer to run down before they generate a new correct code.

**Comment by nilsbehlen** [comment]
should be fixed now. The new version is still being processed by apple tho...
