### ISSUE TITLE
build question

### ISSUE THREAD

**Issue by Jaapdijkshoorn** [privacyidea/privacyidea-authenticator-ios#16]
When i pull branch v2.0.0push and try to build it locally with Xcode i get the following error:

error: Build input files cannot be found: ‘/Users/nils/Desktop/piauthenticator/privacyIDEA Authenticator/Token.swift’, ‘/Users/nils/Desktop/piauthenticator/privacyIDEA Authenticator/Storage.swift’, ‘/Users/nils/Desktop/piauthenticator/privacyIDEA Authenticator/PushAuthRequest.swift’, ‘/Users/nils/Desktop/piauthenticator/privacyIDEA Authenticator/FirebaseConfig.swift’, ‘/Users/nils/Desktop/piauthenticator/privacyIDEA Authenticator/Model.swift’

Looks like something locally was included that is missing in th esource tree?

OR am i doing something wrong?

**Comment by nilsbehlen** [comment]
Hi,
it seems like the absolute file paths were saved somewhere in the project configuration.
I do not know exactly how xcode saves the project files (i.e. where to change it) but you could start a new project and just add the files to it.
Hope that helps.

**Comment by basvandervlies** [comment]
@nilsbehlen is this issue also holding back publishing the new app in the App Store?

**Comment by nilsbehlen** [comment]
Hi,
no thats not the issue, there were some changes requested to the PR, but the new version should become available next week.

**Comment by basvandervlies** [comment]
> Hi,
> no thats not the issue, there were some changes requested to the PR, but the new version should become available next week.

Thanks a lot.  Looking forward to test it in our environment ;-)

**Comment by droobah** [comment]
as a quick note, to fix this issue, you will just need to switch the few 'Absolute Path' to 'Relative to Group', and then tap the little Folder icon to relocate the file if needed for the following:

privacyIDEA Authenticator->Model (whole folder)
privacyIDEA Authenticator->Utilities->Storage.swift (single file)

**Comment by droobah** [comment]
I've fixed the build issue over at https://github.com/droobah/privacyidea-authenticator-ios

I've also made the UI work properly in Dark Mode and fixed some constraint issues in the UI causing it to break/act strange on some screen sizes.

I can create a pull request if it's wanted.

**Comment by nilsbehlen** [comment]
sure, a PR would be welcome!

**Comment by droobah** [comment]
Cool, I'll get one going shortly.  I've also done the following:

- Push notifications to work under all states (foreground, background, and terminated)
- Push notifications with 'Allow' action that can be tapped from the notification center or watch (requires a few changes to the message payload in the FirebaseProvider.py in privacyIDEA)

**Comment by nilsbehlen** [comment]
closed via #18
