### ISSUE TITLE
2step enrollment: modal dialog not modal

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea-authenticator-ios#20]
During 2step enrollment there is this dialog that displays the phone part of the secret key.
It has an OK button.

But clicking everywhere *outside* of the dialog also closes this dialog.

On smartphones that have a very quick screensaver, where the screen turns dark very quickly this leads to the following problem:
The user taps anywhere (outside) of the screen and the dialog will close. So there is not enough time to read and type the phone part.

The dialog should only close, when "OK" is tapped.
(The Android App has the same issue)

**Comment by nilsbehlen** [comment]
Could not reproduce this with v2.0.4 on iOS 13.1.3. 
Maybe @NuvandaPV can try to reproduce it?
