### ISSUE TITLE
App must be restarted after importing push token

### ISSUE THREAD

**Issue by cbr46** [privacyidea/privacyidea-authenticator-ios#33]
After importing a push token the app has to be restarted in order to receive any push notifications.

Is this an expected behavior?

iOS version: 13.6
App version: 2.0.4

**Comment by lindenaar** [comment]
I can confirm that the first time you enroll a token, the application needs to be restarted.

After that, removing and enrolling a new token just works, no need to restart it seems.

iOS version 14
App version: 2.0.4
